### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#134]
# [The roadmap was move to the wiki](https://github.com/pattern-lab/patternlab-node/wiki/Roadmap)

**Comment by bmuenzenmeyer** [comment]
## v0.10.1
- [ ] CHECK FOR ANY OTHER MAJOR GAPS TO [PL PHP V1](https://github.com/pattern-lab/patternlab-php)
- [ ] BUG: [Lineage not working for patterns with pattern parameters](https://github.com/pattern-lab/patternlab-node/issues/135)
- [ ] ADD: Unit test coverage of some of the newer features / newly modular code

## v0.11.0
- [ ] ADD: [Support List Item Data](https://github.com/pattern-lab/patternlab-node/issues/92)
- [ ] ADD: [Support for ignoring _directories](https://github.com/pattern-lab/patternlab-node/issues/128)
- [ ] ADD: [Support a fluid viewport](https://github.com/pattern-lab/patternlab-node/issues/122)
- [ ] FIX: [Pseudopatterns should support the ##-ordering system](https://github.com/pattern-lab/patternlab-node/issues/121)

## v0.12.0
- [ ] ADD: [Support for style modifiers](https://github.com/pattern-lab/patternlab-node/issues/95)
- [ ] ADD: [Move _patternlab-files out of source to make upgrading easier for users](https://github.com/pattern-lab/patternlab-node/issues/133)

## v0.13.0
- [ ] ADD: [Gulp support](https://github.com/pattern-lab/patternlab-node/issues/57)
- [ ] ADD: [Reinvestigate page-follow](https://github.com/pattern-lab/patternlab-node/issues/103)
- [ ] FIX: [Support the auto-reload and page follow options as part of BrowserSync support ](https://github.com/pattern-lab/patternlab-node/issues/102)

## v1.0.0
- [ ] FINISH: [Add More Unit Tests](https://github.com/pattern-lab/patternlab-node/issues/97)
- [ ] FIX: [Look to see if example pattern vendor js needs to be updated ](https://github.com/pattern-lab/patternlab-node/issues/85)

## Post v1.0.0
- [ ] ADD: [Show "CSS" and "JS" tabs in code section](https://github.com/pattern-lab/patternlab-node/issues/113)
- [ ] ADD: [adding multi-compiler functionality](https://github.com/pattern-lab/patternlab-node/pull/126)

**Comment by bmuenzenmeyer** [comment]
I compared the patternlab documentation to the pl node feature set and I think that all major features are on the roadmap. If someone finds something with _PL PHP v1_ that is omitted here please let me know.
