### ISSUE TITLE
Support Configurable Pattern Lab Paths/Filesystem

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#220]
This is the wrap up from [Configurable paths galore](https://github.com/pattern-lab/patternlab-node/pull/216)

## TODO

- [x] Initial work
- [x] gruntfile @bmuenzenmeyer
- [x] [dev branch: Add copy commands for public/styleguide assets](https://github.com/pattern-lab/patternlab-node/issues/229)
       - (short term fix - until https://github.com/pattern-lab/patternlab-node/issues/133 lands)
- [x] [dev branch: Config Paths only work with `./` prefix](https://github.com/pattern-lab/patternlab-node/issues/222)
- [x] more testing - grunt
   - **absolute**
   - [x] Move source.root directory to an arbitrary absolute path
   - [x] Move source.patterns directory to an arbitrary absolute path
   - [x] Move source.styleguide directory to an arbitrary absolute path   
   - [x] Move source.fonts directory to an arbitrary absolute path   
   - [x] Move public.root directory to an arbitrary absolute path
   - **relative**   
   - [x] Move source.root directory to an arbitrary relative path
   - [x] Move source.patterns directory to an arbitrary relative path
   - [x] Move source.styleguide directory to an arbitrary relative path
   - [x] Move source.fonts directory to an arbitrary absolute path   
   - [x] Move public.root directory to an arbitrary relative path
- [x] more testing - gulp
   - **absolute**
   - [x] Move source.root directory to an arbitrary absolute path
   - [x] Move source.patterns directory to an arbitrary absolute path
   - [x] Move source.styleguide directory to an arbitrary absolute path   
   - [x] Move source.fonts directory to an arbitrary absolute path   
   - [x] Move public.root directory to an arbitrary absolute path
   - **relative**   
   - [x] Move source.root directory to an arbitrary relative path
   - [x] Move source.patterns directory to an arbitrary relative path
   - [x] Move source.styleguide directory to an arbitrary relative path
   - [x] Move source.fonts directory to an arbitrary absolute path   
   - [x] Move public.root directory to an arbitrary relative path
- [x] final check with Geoff
- [x] final check with Evan

**Comment by bmuenzenmeyer** [comment]
Made some progress on this tonight.

**Comment by geoffp** [comment]
:+1:

**Comment by bmuenzenmeyer** [comment]
@geoffp any further testing you can do on this is appreciated.
some thoughts, that I will likely do too:

- [ ] Move source.root directory to an arbitrary absolute path
- [ ] Move source.patterns directory to an arbitrary absolute path
- [ ] Move public.root directory to an arbitrary absolute path
- [ ] Move source.root directory to an arbitrary relative path
- [ ] Move source.patterns directory to an arbitrary relative path
- [ ] Move public.root directory to an arbitrary relative path

**Comment by bmuenzenmeyer** [comment]
@geoffp @EvanLovely 

This is ready in `dev` for testing on your end, if you get a chance. I feel like I gave grunt a decent workout. I will do gulp next chance I get too, but anything you can test would be appreciated!

Testhing this and documenting #221 is all that remains for 1.1.0 to ship
