### ISSUE TITLE
EPIC: Implement Improved Pattern Metadata Parsing

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#376]
Implement the following per https://github.com/pattern-lab/the-spec/issues/16
- [x] parse state out of a pattern's .md Front Matter and map to a pattern's patternState proprerty
- [x] remove `setPatternState()` from pattern_assembler
- [x] parse order out of a pattern's .md Front Matter and use to override any file order prior to rendering
- [X] parse title out of a pattern's .md Front Matter and use to override the filename 
- [x] parse additional keys ouf of a pattern's .md Front Matter
- [x] display additional keys inside {{patternDescAdditions}}   -- moved to ExtraOutput in data
- [ ] parse hidden out of a pattern's .md Front Matter and use to hide pattern from all direct individual or subtype rendering similar to _underscoredPattern.mustache today. These patterns should still be include-able as partials
- [ ] parse ~excludeFromStyleguide~ `noviewall` (or a better name) out of a pattern's .md Front Matter and use to omit pattern from all rendering
- [ ] parse `tags` out of a pattern's .md Front Matter and ... ??? (available in a future search enhancement?)
- [ ] parse `links` out of a pattern's .md Front Matter and display in a future are of the front-end
- [ ] unit test coverage

**Comment by tburny** [comment]
What is the state of this?

**Comment by bmuenzenmeyer** [comment]
The above list is still accurate, with my taking potshots at different items every so often. As you can see, there is some diminishing returns as you get down the list, as we haven't fully realized a usage of some metadata - but things like `order` and `state` were no-brainers because they removed metadata from the filename itself. You can say the same about `hidden`, whih is the next we should tackle.

**Comment by jdagerot** [comment]
According to the discussion on gitter we could have a discussion about if the code should store all frontmatter keys no matter of the keynames and values, or really just parse a few.

I believe it would be much more flexible to just store the whole parsed markdown object into the pattern, so everyone easily can implement their own keys.

[I made a pull request about this #676](https://github.com/pattern-lab/patternlab-node/pull/676)

**Comment by EvanLovely** [comment]
I've implemented several of these over in the PHP version here: https://github.com/pattern-lab/patternlab-php-core/pull/137

For the `-button.mustache` behavior which removes it from View All, but not menu, it was called `noviewall` in the code so that's the name I went with instead of `excludeFromStyleguide`, so I'll suggest that for here. I'm totally happy to add that as an extra one (i.e. could do `excludeFromStyleguide: true` or `noviewall: true`) if you'd like.

**Comment by EvanLovely** [comment]
PS I've set it so `order` gets passed in from MD files, but it doesn't reorder patterns on the PHP side until this is done: https://github.com/pattern-lab/patternlab-php-core/issues/138

**Comment by bmuenzenmeyer** [comment]
@EvanLovely 

> For the -button.mustache behavior which removes it from View All, but not menu, it was called noviewall in the code so that's the name I went with instead of excludeFromStyleguide, so I'll suggest that for here. I'm totally happy to add that as an extra one (i.e. could do excludeFromStyleguide: true or noviewall: true) if you'd like.

updated my issue, thanks. You can see it's a bit WIP.

> PPS I'm passing through tags and links just as you are so we're ready to implement those whenever.

we could consider making these first class citizens, not hanging them off of `extraOutput` like https://gist.github.com/bmuenzenmeyer/fb51a07a5089422ee0b1aa036714b996 illustrates, since we are pretty certain we will be doing something with them.
