### ISSUE TITLE
Pattern Lab Node 1.2

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#38]
Drive progress toward adherence to the [Pattern Lab specification](https://github.com/pattern-lab/the-spec/blob/draft/SPEC.md):
- [x] #35 4.1. Atomic Design Naming Convention Not Required
- [x] #6 4.6.3. Annotations
- [x] #36  5.5. Version Command
- [x] #37  5.6. Help Command

Miscellaneous Fixes and Improvements
- [x] #26 Code Option Not Working and Some Icons Not Showing
- [x] #30 Version Mustache with NPM
- [x] #31 Published to NPM 
- [x] Pattern compilation only support
