### ISSUE TITLE
UI Builder Rewrite ToDo / Issues

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#423]
Bucket for TODOs left on this total effort.

- [x] Pattern Type View All
- [ ] View All should be at the end of each menu / submenu
- [ ] More unit tests

**Comment by bmuenzenmeyer** [comment]
Closing due to lack of specificity
