### ISSUE TITLE
EPIC: Implement Basic Support for Plugins

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#432]
- [x] Install Plugin 
- [x] Output plugin config
- [x] Output structure to frontend
- [x] Load Plugin 
- [x] Emit Events
   - http://blog.yld.io/2015/12/15/using-an-event-emitter/#.V77fNZgrKUk
   - https://nodejs.org/api/events.html
- [x] Subscribe to Events
- [x] **In progress** Proof of concept: [front-end plugin](https://github.com/pattern-lab/plugin-node-tab)
- [x] Documentation
- [ ] Research and implement event emitter best practices
- [ ] Implement `disablePlugin()` `enablePlugin()`

**Comment by bmuenzenmeyer** [comment]
@dmolsen is it fair to say that [this php core search for dispatch](https://github.com/pattern-lab/patternlab-php-core/search?utf8=%E2%9C%93&q=dispatch) is a decent map of all the possible plugin event hooks?
