### ISSUE TITLE
Convert to monorepo

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#803]
This is our "Target" for a hackday today. 
Wish us luck!

Goals:

- [x] lerna.js | https://github.com/lerna/lerna 
- [x] document repeatable pattern to convert existing repos into monorepo
- [x] move patternlab-node (this repo) with history
- [x] move edition-node-gulp with history
- [x] move edition-node with history
- [x] move patternengine-node-mustache
- [x] move patternengine-node-react
- [x] create uikit-default - https://github.com/pattern-lab/uikit-default
   - [x] styleguidekit-mustache-default (history would be great here)
   - [x] styleguidekit-assets-default (history would be great here) 
- [ ] fix links everywhere
- [ ] update installation and contributing docs

### Test

- [x] locally linked and runnable pattern lab node

### Stretch

- [ ] deployment procedures (https://github.com/atlassian/lerna-semantic-release ?)
- [x] move patternengine-node-underscore
- [x] move patternengine-node-handlebars
- [x] move patternengine-node-twig
- [x] move patternengine-node-liquid
- [x] move plugin-node-tab
- [x] move live-server
- [x] move patternlab-node-cli
- [ ] move patternengine-node-nunjucks
- [ ] move edition-node-grunt

**Comment by bradfrost** [comment]
Good luck! I feel there needs to be a Transoformer-style mascot for MONOREPO

**Comment by bmuenzenmeyer** [comment]
```
lerna init --independent --exact
lerna import <<path/to/local/git/repo>> --flatten
```

without `flatten`, any conflicts in the target repo would cause a rollback.

**Comment by geoffp** [comment]
Huge success! We do still need to figure out how editions get installed, since you can’t just git clone ‘me anymore. But our sense is that the CLI should do this.

**Comment by bmuenzenmeyer** [comment]
Omitted edition-node-grunt - it's obsolete unless someone wants to take it up.

https://github.com/pattern-lab/edition-node-grunt/issues/31

**Comment by Ryuno-Ki** [comment]
@bradfrost [Autobot by Moonlily5](http://fav.me/d8hm3yc) may be for you then :-)
